# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNJudo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNJudo
	pod "JudoKitObjC", :git => 'https://github.com/radhakrishnant2s/JudoKitObjC.git', :branch => 'master'
end
